name: Consume Distributed Validation Layer
on:
  push:
    branches:
      - demo-1
      - master
jobs:

  validation:
    uses: YaphetS0206/matrix-workflow/.github/workflows/distributed-validation.yml@demo-1
    
    