name: Consume Distributed Validation Layer
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'The environment to deploy for'
        default: 'dev'
        required: true
        type: string


permissions:
  contents: read
  security-events: write
  
jobs:
  validation:
    uses: YaphetS0206/matrix-workflow/.github/workflows/distributed-validation.yml@demo-2
    with:
      python-versions: '[3.11, 3.12]'
      min-coverage: 80
      max-high-vulns: 0